apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: glbu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: glbu
    app.kubernetes.io/part-of: byoc-app-drcg
  name: glbu
spec:
  rules:
  - host: glbu-byoc-iljf-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-fnkwb.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: glbu
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
